#!/usr/bin/env python3
"""
Quick setup script for Neon database configuration.
Helps configure .env file with Neon connection string.
"""

import os
import secrets
import sys
from pathlib import Path


def generate_secret_key():
    """Generate a secure secret key for JWT tokens."""
    return secrets.token_hex(32)


def validate_neon_url(url):
    """Basic validation of Neon connection string format."""
    if not url:
        return False

    # Check for postgresql:// prefix
    if not url.startswith("postgresql://") and not url.startswith("postgres://"):
        return False

    # Check for neon.tech domain
    if "neon.tech" not in url:
        print("⚠️  Warning: URL doesn't contain 'neon.tech' - are you sure this is a Neon connection string?")

    # Check for sslmode
    if "sslmode=require" not in url:
        print("⚠️  Warning: Connection string should include '?sslmode=require' for secure connections")
        print("   Neon requires SSL connections.")
        return False

    return True


def main():
    print("=" * 70)
    print("Notetime - Neon Database Setup Script")
    print("=" * 70)
    print()

    # Check if running in project root
    project_root = Path(__file__).parent.parent
    env_file = project_root / ".env"
    env_example = project_root / ".env.example"

    print(f"📁 Project root: {project_root}")
    print()

    # Check if .env already exists
    if env_file.exists():
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (yes/no): ").strip().lower()
        if response not in ["yes", "y"]:
            print("❌ Setup cancelled. Your existing .env file was not modified.")
            sys.exit(0)
        print()

    # Get Neon connection string
    print("Step 1: Neon Connection String")
    print("-" * 70)
    print("Get your connection string from: https://console.neon.tech")
    print("  1. Go to your project dashboard")
    print("  2. Click 'Connection Details'")
    print("  3. Copy the connection string")
    print()
    print("It should look like:")
    print("postgresql://user:pass@ep-xxx-xxx.region.aws.neon.tech/dbname?sslmode=require")
    print()

    while True:
        database_url = input("Paste your Neon connection string: ").strip()

        if validate_neon_url(database_url):
            break
        else:
            print("❌ Invalid connection string format. Please try again.")
            print()

    # Fix postgres:// to postgresql:// if needed
    if database_url.startswith("postgres://"):
        database_url = database_url.replace("postgres://", "postgresql://", 1)
        print("✅ Fixed URL prefix: postgres:// → postgresql://")

    print()

    # Generate secret key
    print("Step 2: JWT Secret Key")
    print("-" * 70)
    secret_key = generate_secret_key()
    print(f"✅ Generated secure secret key: {secret_key[:16]}...")
    print()

    # JWT settings
    print("Step 3: JWT Configuration")
    print("-" * 70)
    algorithm = input("JWT Algorithm (default: HS256): ").strip() or "HS256"

    token_expire = input("Access token expiration in minutes (default: 10080 = 7 days): ").strip()
    token_expire = token_expire if token_expire else "10080"

    try:
        int(token_expire)
    except ValueError:
        print("⚠️  Invalid number, using default: 10080")
        token_expire = "10080"

    print()

    # Write .env file
    print("Step 4: Writing Configuration")
    print("-" * 70)

    env_content = f"""# Notetime Environment Variables
# Generated by setup_neon.py

# Database Configuration - Neon (Serverless PostgreSQL)
DATABASE_URL={database_url}

# JWT Secret Key
SECRET_KEY={secret_key}

# JWT Algorithm
ALGORITHM={algorithm}

# JWT Access Token Expiration in minutes
ACCESS_TOKEN_EXPIRE_MINUTES={token_expire}
"""

    with open(env_file, "w") as f:
        f.write(env_content)

    print(f"✅ Created .env file at: {env_file}")
    print()

    # Next steps
    print("=" * 70)
    print("Setup Complete! 🎉")
    print("=" * 70)
    print()
    print("Next steps:")
    print()
    print("1. Install dependencies (if not done yet):")
    print("   pip install -r requirements.txt")
    print()
    print("2. Initialize the database:")
    print("   python -m notetime.create_db")
    print()
    print("3. (Optional) Seed with demo data:")
    print("   python -m notetime.seed")
    print()
    print("4. Start the application:")
    print("   uvicorn notetime.main:app --reload")
    print()
    print("5. Visit http://localhost:8000/docs to test the API")
    print()
    print("For more information, see NEON-DEPLOYMENT.md")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Error: {e}")
        sys.exit(1)
